---
title: "Admixture_visualization_markdown"
author: "Joseph Mulama Atemia"
date: "24/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r libraries, echo=TRUE}
library("pophelper")
library("gridExtra")
library("gtable")
library("label.switching")
library("tidyr")
library("ggplot2")
```

## Import files and generate qlist object

```{r loading data, echo=TRUE}
# import metadata files
meta_data <- read.delim("../data/maize_samples.txt", header=T, stringsAsFactors=F)

# filter data to include only maize samples
#View(meta_data) # inspecting to allow for subsetting using dplyr 

# read the admixture run file into a ‘qlist’ object
qlist <- readQ("../data/maize.3.Q",indlabfromfile = F)

# Adding group lables
onelabset <- meta_data[,2,drop=F]
twolabset <- meta_data[,1:2]

# Adding a new column by combining the sample ids with respective altitudes for plotting. Some individuals were sampled from the same altitude
meta_data$sampleID_altitude <- paste(meta_data$sample_id, meta_data$altitude, sep="_")

# Adding labels
rownames(qlist[[1]]) <- meta_data$sampleID_altitude
```

## Plotting admixture plot
```{r plot admixture, echo=TRUE}
# Ploting the admixture results
p1 <- plotQ(qlist[1],exportplot=T,returnplot=T, showyaxis=T, showgrplab = F,
            ordergrp=TRUE, grplab = onelabset, basesize=11, useindlab = T, # Ordering by spp.
            showindlab = T, subsetgrp="Zea mays ssp. mays", sortind = "all", # Selecting only maize samples
            showtitle=T,showsubtitle=T,titlelab="Admixture plot", titlesize = 14, # Adding title and subtitle
            subtitlelab="Population structure of Zea mays ssp. mays.",
            subtitlesize = 12, showlegend=T,legendkeysize=8,legendtextsize=10,
            legendlab=c("Cluster 1", "Cluster 2","Cluster 3"), indlabsize = 4,
            imgtype = "pdf",
            exportpath= "../results",
            outputfilename = "../results/admixture_plot",
            height = 4,
            width = 8,
            dpi = 300,
            units = "inches",
            theme = "theme_grey") # labeling the sub populations

p1$plot[[1]]
```

## Plotting multiline admixture plot
```{r plot multiline admixture, echo=TRUE}
p <- plotQMultiline(qlist,exportplot=T,returnplot=T, spl = 55, showyaxis=T, 
                    ordergrp=TRUE, grplab = onelabset, basesize=11, useindlab = T, # Ordering by spp.
                    showindlab = T, subsetgrp="Zea mays ssp. mays", sortind = "all", # Selecting only maize samples
                    showtitle=T,showsubtitle=T,titlelab="Admixture plot", titlesize = 14, # Adding title and subtitle
                    subtitlelab="Population structure of Zea mays ssp. mays.",
                    subtitlesize = 12, showlegend=T,legendkeysize=8,legendtextsize=10,
                    legendlab=c("Cluster 1", "Cluster 2","Cluster 3"), indlabsize = 7,
                    imgtype = "pdf", # plotting
                    outputfilename = "../results/multiline_admixture_plot",
                    exportpath= "../results",
                    height = 10,
                    width = 8,
                    dpi = 300,
                    units = "in",
                    theme = "theme_grey") # labeling the sub populations

grid.arrange(p$plot[[1]][[1]]) # plotting the Multiline Plot
```

